# Generated by Django 5.2.13 on 2026-04-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('listings', '0001_initial'),
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='meetup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='meetups.meetup'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='listings.listing'),
        ),
    ]
